sas-viya/metadata.json
shortened metadata.json description
=> Update metadata to have shorter description

sas-viya/README.md, sas-viya/metadata.json
Updated metadata.json to add type and schema
=> - Updated readme.md to fix absolute link

sas-viya/azuredeploy.json, sas-viya/azuredeploy.parameters.json, sas-viya/file_tree.txt
=> Sas develop

sas-9.4m7-VA-MPP/ansible/install_hadoop.yaml, sas-9.4m7-VA-MPP/ansible/install_hadoop_plugin.yaml, sas-9.4m7-VA-MPP/file_tree.txt, sas-9.4m7-VA-MPP/scripts/install_runner/install_runner.sh
=> (AZUREVAVS-38) Initial:SAS Plug-in for Hadoop

sas-viya/ansible/roles/post_deployment/deploy_saswork_restart_service/files/setupSasWorkOnStartup.sh
=> (AZUREVIYA-306) Fix configuration of SASWORK dir

sas-viya/scripts/ansiblecontroller_prereqs.sh
=> (AZUREVIYA-308) Installing pip version 20.3.4

sas-viya/README.md
Add sentence about deployment failures due to pip version.  Add to Quickstart in sassoftware repository only.
*
*
*
=> (AZUREVIYA-309) Deployment failures-pip version

sas-9.4m7-VA-MPP/ansible/download_mirror_and_licenses.yaml, sas-9.4m7-VA-MPP/scripts/install_runner/install_runner.sh
=> (AZUREVAVS-61) Download mirror from blob to correct folder.

sas-9.4m7-VA-MPP/scripts/install_runner/install_runner.sh
=> (AZUREVAVS-43) Copy plan file to sasshare

sas-9.4m7-VA/scripts/SetupJump.sh, sas-9.4m7-VA/scripts/SetupNonJump.sh, sas-9.4m7-VA/scripts/install_runner/install_runner.sh
=> (AZUREVAVS-63) Increase attribute cache timeout for sasshare

sas-9.4m7-VA-MPP/ansible/install_sas.yaml, sas-9.4m7-VA-MPP/ansible/update_responsefiles.yaml, sas-9.4m7-VA-MPP/file_tree.txt, sas-9.4m7-VA-MPP/responsefiles/mpp_metadata.txt.j2, sas-9.4m7-VA-MPP/responsefiles/mpp_metadata_node.txt.j2
=> (AZUREVAVS-64) Move metadata installation back to a single response file

sas-viya/metadata.json
=> (AZUREVIYA-322) Fix issue with pip3

sas-viya/scripts/ansiblecontroller_prereqs.sh
=> (AZUREVIYA-322) Update pip URL

sas-9.4m7-VA/azuredeploy.json
=> (AZUREVAVS-64) Add instance type and set metadata VM count to 1

sas-9.4m7-VA-MPP/azuredeploy.json
=> (AZUREVAVS-64) Add instance type and remove Metadata VM Count parameter

sas-9.4m7-VA/scripts/SetupNonJump.sh
=> (AZUREVAVS-42) Remove workaround for SUSE issue

sas-9.4m7-VA-MPP/azuredeploy.json
=> (AZUREVAVS-44) Long Resource Group names cause connection error

sas-9.4m7-VA-MPP/ansible/run_sas_servers.yaml
=> (AZUREVAVS-32) Make status_sas.sh more user-friendly

sas-9.4m7-VA-MPP/scripts/SetupJump.sh, sas-9.4m7-VA-MPP/scripts/start_sas.sh, sas-9.4m7-VA-MPP/scripts/stop_sas.sh
Installing azure cli on jumpvm and update start/stop sas scripts.
=> (AZUREVAVS-72) Install azure cli

sas-9.4m7-VA/plan.20w34.xml
=> (AZUREVAVS-74) Updates to support 21w08

sas-9.4m7-VA-MPP/azuredeploy.json
=> (AZUREVAVS-44) Reduce the allowed size of the domain to account for long region names

sas-9.4m7-VA-MPP/ansible/install_hadoop.yaml, sas-9.4m7-VA-MPP/ansible/install_hadoop_plugin.yaml, sas-9.4m7-VA-MPP/scripts/install_runner/install_runner.sh
=> (AZUREVAVS-76) Fix issues in hadoop and hadoop plugin installation

sas-9.4m7-VA/scripts/start_sas.sh, sas-9.4m7-VA/scripts/stop_sas.sh
=> (AZUREVAVS-68) Updated path to az command

sas-9.4m7-VA-MPP/scripts/SetupNonJump.sh
=> (AZUREVAVS-72) Added missing mounts in fstab

sas-9.4m7-VA/scripts/install_runner/install_runner.sh
=> (AZUREVAVS-80) Deployments should fail if SAS installation fails

sas-9.4m7-VA-MPP/scripts/install_runner/install_runner.sh
=> (AZUREVAVS-80) Deployment should fail if sas installation fails

sas-9.4m7-VA-MPP/ansible/update_wip_server.yaml, sas-9.4m7-VA-MPP/scripts/install_runner/install_runner.sh
=> (AZUREVAVS-81) Use correct password for postgres

sas-9.4m7-VA-MPP/azuredeploy.json
=> (AZUREVAVS-83) Remove the ? from parameter name

sas-9.4m7-VA/ansible/update_wip_server.yaml
=> (AZUREVAVS-80) Handle pipes in password by quoting export

sas-9.4m7-VA-MPP/plan.xml
=> (AZUREVAVS-85) Update plan file for 21w17

sas-9.4m7-VA-MPP/README.md
Incorporated peer review comments.
*
*
*
=> (AZUREVAVS-45) Comments from editor

sas-9.4m7-VA-MPP/azuredeploy.json
=> (AZUREVAVS-89) Remove smaller sizes for SAS VMs

sas-9.4m7-VA-MPP/ansible/create_metadata_update_scripts.yaml, sas-9.4m7-VA-MPP/ansible/update_midtier_files.yaml, sas-9.4m7-VA-MPP/azuredeploy.json, sas-9.4m7-VA-MPP/responsefiles/setSASWebUrls.txt.j2
=> (AZUREVAVS-91) Enable SAS Environment Manager access via load balancer

sas-9.4m7-VA-MPP/ansible/run_hadoop_servers.yaml, sas-9.4m7-VA-MPP/ansible/run_sas_servers.yaml, sas-9.4m7-VA-MPP/scripts/start_sas.sh, sas-9.4m7-VA-MPP/scripts/stop_sas.sh
=> (AZUREVAVS-92) Adding Hadoop servers to start script.

sas-9.4m7-VA-MPP/file_tree.txt
=> (AZUREVAVS-92) Add hadoop servers to start script

sas-9.4m7-VA-MPP/ansible/download_mirror_and_licenses.yaml
=> (AZUREVAVS-95) Fix path for plan file

sas-9.4m7-VA-MPP/azuredeploy.json
=> (AZUREVAVS-94) Set the lower range of vaworker nodes to 2

sas-9.4m7-VA-MPP/scripts/SetupNonJump.sh
=> (AZUREVAVS-84) Start atd daemon on SAS VMs

sas-9.4m7-VA-MPP/azuredeploy.json, sas-9.4m7-VA-MPP/scripts/SetupJump.sh
=> (AZUREVAVS-97) Azure recommended fix for cert expiration issue

sas-viya/scripts/ansiblecontroller_prereqs.sh, sas-viya/scripts/nonansiblecontroller_prereqs.sh
=> (AZUREVIYA-333) Yum fix to handle issues with expiring certs

sas-9.4m7-VA-MPP/README.md, sas-9.4m7-VA-MPP/metadata.json
=> (AZUREVAVS-46) Pull Request Prep

sas-9.4m7-VA-MPP/azuredeploy.json, sas-9.4m7-VA-MPP/azuredeploy.parameters.json
=> (AZUREVAVS-98) Restrict location parameter to regions supporting AZs

sas-9.4m7-VA-MPP/README.md, sas-9.4m7-VA-MPP/ansible/install_hadoop.yaml, sas-9.4m7-VA-MPP/azuredeploy.json, sas-9.4m7-VA-MPP/scripts/install_runner/install_runner.sh
=> (AZUREVAVS-101) Resolve best practice issues.

sas-9.4m7-VA-MPP/README.md, sas-9.4m7-VA-MPP/ansible/install_hadoop.yaml, sas-9.4m7-VA-MPP/azuredeploy.json, sas-9.4m7-VA-MPP/scripts/install_runner/install_runner.sh
Reverts sassoftware/azure-quickstart-templates#143
=> Revert "(AZUREVAVS-101) Resolve best practice issues."

sas-9.4m7-VA-MPP/azuredeploy.json
Reverts sassoftware/azure-quickstart-templates#146
=> Revert "(AZUREVAVS-101) Add choosable values for jumpvm size."

application-workloads/sas/sas-9.4m7-va-mpp/plan.xml
=> (AZUREVAVS-102) 21w26 support

application-workloads/sas/sas-9.4m7-va-mpp/metadata.json
=> (AZUREVAVS-121) Fixing typo

application-workloads/sas/sas-viya/azuredeploy.json
=> (AZUREVIYA-343) Supporting new GitHub path

application-workloads/sas/sas-viya/scripts/ansiblecontroller_prereqs.sh, application-workloads/sas/sas-viya/scripts/nonansiblecontroller_prereqs.sh
=> (AZUREVIYA-333) Fixing deployments fail with certificate errors

application-workloads/sas/sas-9.4m7-va-mpp/azuredeploy.json, application-workloads/sas/sas-9.4m7-va-mpp/subtemplates/installextension.json, application-workloads/sas/sas-9.4m7-va-mpp/subtemplates/run_script.json
=> (AZUREVAVS-101) Update apiVersions

application-workloads/sas/sas-9.4m7-va-mpp/azuredeploy.json, application-workloads/sas/sas-9.4m7-va-mpp/subtemplates/installextension.json, application-workloads/sas/sas-9.4m7-va-mpp/subtemplates/run_script.json
Reverts sassoftware/azure-quickstart-templates#158
=> (AZUREVIYA-353) Update apiVersion and PrimaryUserName parameter

application-workloads/sas/sas-viya/azuredeploy.json, application-workloads/sas/sas-viya/azuredeploy.parameters.json, application-workloads/sas/sas-viya/nestedtemplates/createNetworkSubtemplate.json, application-workloads/sas/sas-viya/nestedtemplates/run_ansible_script.json
=> (AZUREVIYA-353) Update apiVersions and PrimaryUserName parameter

application-workloads/sas/sas-9.4m7-va-mpp/azuredeploy.json, application-workloads/sas/sas-9.4m7-va-mpp/subtemplates/installextension.json, application-workloads/sas/sas-9.4m7-va-mpp/subtemplates/run_script.json
=> (AZUREVAVS-101) Updating apiVersions

application-workloads/sas/sas-9.4m7-va-mpp/azuredeploy.json
=> (AZUREVAVS-101) Adding Primary User Name parameter restrictions

application-workloads/sas/sas-viya/README.md, application-workloads/sas/sas-viya/azuredeploy.json
=> (AZUREVIYA-353) Updates for PrimaryUserName parameter

application-workloads/sas/sas-viya/azuredeploy.json, application-workloads/sas/sas-viya/nestedtemplates/run_ansible_script.json
=> (AZUREVIYA-353) Update uri() function calls

application-workloads/sas/sas-9.4m7-va-mpp/azuredeploy.json, application-workloads/sas/sas-9.4m7-va-mpp/subtemplates/run_script.json
=> (AZUREVAVS-101) Update azure uri() functions and apiVersions

application-workloads/sas/sas-viya/README.md, application-workloads/sas/sas-viya/azuredeploy.json, application-workloads/sas/sas-viya/nestedtemplates/run_ansible_script.json
=> (AZUREVIYA-345) Release 1.4.8

application-workloads/sas/sas-viya/azuredeploy.json
=> (AZUREVIYA-353) Update apiVersions

application-workloads/sas/sas-viya/azuredeploy.json
=> (AZUREVIYA-353) Adding _artifactsLocation description to template

application-workloads/sas/sas-viya/README.md
Specify to use the default value for artifactsLocation parameter.
*
*
*
=> (AZUREVIYA-353) artifactsLocation parameter

application-workloads/sas/sas-viya/README.md
=> (AZUREVIYA-354) Release 1.4.8

application-workloads/sas/sas-viya/azuredeploy.json, application-workloads/sas/sas-viya/azuredeploy.parameters.json
=> (AZUREVIYA-354) Removing PrimaryUserName defaultValue

application-workloads/sas/sas-9.4m7-va-mpp/azuredeploy.json, application-workloads/sas/sas-9.4m7-va-mpp/subtemplates/installextension.json, application-workloads/sas/sas-9.4m7-va-mpp/subtemplates/run_script.json
=> Resolve merge conflicts

application-workloads/sas/sas-9.4m7-va-mpp/azuredeploy.json
=> Cleaning up previous merge conflicts

application-workloads/sas/sas-9.4m7-va-mpp/azuredeploy.json
=> Cleaning up previous merge conflict

application-workloads/sas/sas-9.4m7-va-mpp/README.md
Add end of support statement to Azure SAS 9.4 VA/VS Quickstart
*
*
*
=> (MERCURY-224) End of support

application-workloads/sas/sas-viya/README.md
Added end of support statement to Azure Quickstart for Viya 3.5
*
*
*
=> (MERCURY-224) - End of support

sas-viya/README.md
Changes to address:
https://github.com/sassoftware/quickstart-sas-viya-azure/issues/87
=> (AZUREVIYA-332) Template and doc changes for SAS9.4 data loading
